// npm run rebase:review: writes REBASE-REVIEW.md, the sign-off table for rebase.json.
// Uses the same arithmetic as the site, ignoring the sign-off gate so the draft can be read.
import { readFileSync, writeFileSync } from 'node:fs';
import { rebaseSchema } from '../src/lib/rebase-schema';
import { ledgerSchema } from '../src/lib/schema';

const rb = rebaseSchema.parse(JSON.parse(readFileSync('src/data/rebase.json', 'utf8')));
const d = ledgerSchema.parse(JSON.parse(readFileSync('src/data/ledger.json', 'utf8')));
const fy = new Map<string, number>();
for (const l of readFileSync('src/data/deflators.csv', 'utf8').trim().split('\n').slice(1)) {
  const [y, i] = l.split(',');
  if (i) fy.set(y, Number(i));
}
const lab = (s: number) => `${s}/${String((s + 1) % 100).padStart(2, '0')}`;
const idx = (y: string, b: string) => (b === 'financial' ? fy.get(y)! : 0.25 * fy.get(lab(+y - 1))! + 0.75 * fy.get(lab(+y))!);
const fmt = (n: number) => (n >= 1e9 ? `£${+(n / 1e9).toPrecision(3)}bn` : n >= 1e6 ? `£${+(n / 1e6).toPrecision(3)}m` : `£${(+n.toPrecision(3)).toLocaleString('en-GB')}`);

const rows = rb.entries.map((e) => {
  const r = d.rows.find((x) => x.id === e.id)!;
  const i = idx(e.price_year, e.basis);
  return `| ${e.id} | ${r.short || r.item} | ${e.figure} | ${e.price_year} (${e.basis}) | ${i.toFixed(2)} | ${(100 / i).toFixed(3)} | **${fmt(e.amount * (100 / i))}** | ${e.note} |`;
});
const out = `# Rebasing to 2025/26 prices: review for sign-off

Status of \`src/data/rebase.json\`: **${rb.status}**. Nothing rebased appears on the site or in the downloads until the status is \`signed-off\`, with a name and date.

Generated by \`npm run rebase:review\` from \`rebase.json\`, \`ledger.json\` and \`deflators.csv\` (HM Treasury GDP deflators, June 2026 Quarterly National Accounts; 2025/26 = 100). Figures are shown to three significant figures, as they would appear on the site.

## Method

- **Financial year:** ${rb.method.financial}
- **Calendar year:** ${rb.method.calendar}
- **Rules:** ${rb.rules}
- **Label on the site:** "${rb.label}"

Entries marked CHECK are the judgement calls most worth a second look.

## Proposed: ${rb.entries.length} entries

| Id | Entry | Figure rebased | Price year | Deflator | Factor | 2025/26 prices | Note |
|---|---|---|---|---|---|---|---|
${rows.join('\n')}

## Left out: ${rb.excluded.length} entries

| Id | Reason |
|---|---|
${rb.excluded.map((x) => `| ${x.id} | ${x.reason.replace('not rebased: ', '')} |`).join('\n')}

## To sign off

Change \`status\` to \`"signed-off"\` in \`src/data/rebase.json\` and fill in \`signed_off_by\` and \`signed_off_on\`, or tell Claude which rows to change first.
`;
writeFileSync('REBASE-REVIEW.md', out);
console.log(`✓ REBASE-REVIEW.md: ${rb.entries.length} proposed, ${rb.excluded.length} left out`);
